# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
alias nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings
export ZSH="$XDG_CONFIG_HOME/oh-my-zsh"
export VOLTA_HOME="$XDG_DATA_HOME"/volta
export WINEPREFIX="$XDG_DATA_HOME"/wine
export HISTFILE="$XDG_CONFIG_HOME"/zsh/history
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export PATH="/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/games:$HOME/.local/bin"

